### ISSUE TITLE
Hi. Not work default instal in Azure. Can you help?  haven't internet. Inbond Port 51820 open, connected, but internet not work. Vultr Aruba...work fine

### ISSUE THREAD

**Issue by anvikVRN** [complexorganizations/wireguard-manager#131] opened 2021-03-24 12:52 UTC

**Comment by Prajwal-Koirala** [comment] 2021-03-25 02:48
sure.

Please post more details and some logs.

**Comment by SLDay** [comment] 2021-03-26 07:55
Hello Prajwal-Koirala, I think I have the same problem when I use the latest script and fresh AWS Lightsail Ubuntu 20.04 instance.
The steps to reproduce:
1. Create AWS Lightsail instance 1 vCPU, 512 MB RAM with Ubuntu 20.04
2. Open ports for Ping, OpenSSH, 55443/udp
3. Install all latest updates for Ubuntu 20.04
4. Install script with all default options (except port 55443/udp)

After installation when I reboot the instance it is starting up very slow (about 5 minutes). When it finaly boots up DNS is not working, nslookup ends up with error. When I check the Unbound status - that's what I get:

root@ip-172-26-15-234:~# service unbound reload
Job for unbound.service failed.
See "systemctl status unbound.service" and "journalctl -xe" for details.

root@ip-172-26-15-234:~# systemctl status unbound.service
● unbound.service - Unbound DNS server
     Loaded: loaded (/lib/systemd/system/unbound.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2021-03-26 07:38:35 UTC; 12min ago
       Docs: man:unbound(8)
    Process: 491 ExecStartPre=/usr/lib/unbound/package-helper chroot_setup (code=exited, status=0/SUCCESS)
    Process: 526 ExecStartPre=/usr/lib/unbound/package-helper root_trust_anchor_update (code=exited, status=0/SUCCESS)
    Process: 1204 ExecReload=/usr/sbin/unbound-control reload (code=exited, status=1/FAILURE)
   Main PID: 549 (unbound)
      Tasks: 1 (limit: 556)
     Memory: 17.7M
     CGroup: /system.slice/unbound.service
             └─549 /usr/sbin/unbound -d

Mar 26 07:38:34 ip-172-26-15-234 unbound[549]: [549:0] notice: init module 1: validator
Mar 26 07:38:34 ip-172-26-15-234 unbound[549]: [549:0] notice: init module 2: iterator
Mar 26 07:38:35 ip-172-26-15-234 systemd[1]: Started Unbound DNS server.
Mar 26 07:38:35 ip-172-26-15-234 unbound[549]: [549:0] info: start of service (unbound 1.9.4).
Mar 26 07:38:35 ip-172-26-15-234 unbound[549]: [549:0] info: generate keytag query _ta-4f66. NULL IN
Mar 26 07:49:32 ip-172-26-15-234 systemd[1]: Reloading Unbound DNS server.
Mar 26 07:49:32 ip-172-26-15-234 unbound-control[1204]: [1616744972] unbound-control[1204:0] warning: control-enable is 'no' in the config file.
Mar 26 07:49:32 ip-172-26-15-234 unbound-control[1204]: [1616744972] unbound-control[1204:0] error: connect: Connection refused for 127.0.0.1 port 8953
Mar 26 07:49:32 ip-172-26-15-234 systemd[1]: unbound.service: Control process exited, code=exited, status=1/FAILURE
Mar 26 07:49:32 ip-172-26-15-234 systemd[1]: Reload failed for Unbound DNS server.

P.S.: If I install the Wireguard without Unbound (custom DNS) - everything is working fine.

**Comment by Prajwal-Koirala** [comment] 2021-03-26 09:19
Hello,
The issue seems with unbound and DNSSEC, so there is an easy fix for this (Turn off DNSSEC).
```
sed -i "s|auto-trust-anchor-file:|# auto-trust-anchor-file:|" /etc/unbound/unbound.conf
systemctl restart unbound
service unbound restart
```

**Comment by SLDay** [comment] 2021-03-26 09:33
Thank you, it made DNS service working now.

It's strange, "service unbound restart" is working and doesn't give any errors.
However "service unbound reload" still gives the same error about "unbound-control".

```
Mar 26 09:28:43 ip-172-26-15-234 unbound-control[2696]: [1616750923] unbound-control[2696:0] warning: control-enable is 'no' in the config file.
Mar 26 09:28:43 ip-172-26-15-234 unbound-control[2696]: [1616750923] unbound-control[2696:0] error: connect: Connection refused for 127.0.0.1 port 8953
```

**Comment by Prajwal-Koirala** [comment] 2021-03-26 09:37
It seems like the server is trying to use `unbound-control` instead of just `unbound`.

**Comment by SLDay** [comment] 2021-03-26 09:41
Thank you for your support, I will "dig" in that direction. Have a nice day!

**Comment by Prajwal-Koirala** [comment] 2021-03-29 14:53
@anvikVRN
Any update?

**Closed** 2021-05-11 04:46 UTC
